/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.studentmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RT Nexgen
 */
public class staff extends javax.swing.JFrame {

    /**
     * Creates new form staff
     */
    public staff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        address = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        teaarea = new javax.swing.JTextArea();
        txtDate = new javax.swing.JTextField();
        teacherAddBtn = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        tacherEditBtn = new javax.swing.JButton();
        txtQualification = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtName = new javax.swing.JTextField();
        txtmobile = new javax.swing.JTextField();
        staffHeader = new javax.swing.JLabel();
        mobile = new javax.swing.JLabel();
        staffId = new javax.swing.JLabel();
        qualification = new javax.swing.JLabel();
        teacherRemoveBtn = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        teagender = new javax.swing.JLabel();
        teamale = new javax.swing.JRadioButton();
        teafemaile = new javax.swing.JRadioButton();
        staffStartingDate = new javax.swing.JLabel();
        stdClearBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        showdata = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1login = new javax.swing.JMenu();
        jMenu2Student = new javax.swing.JMenu();
        jMenu3Teacher = new javax.swing.JMenu();
        jMenu4Staff = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        address.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        address.setText("Address");

        teaarea.setColumns(20);
        teaarea.setRows(5);
        jScrollPane3.setViewportView(teaarea);

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        teacherAddBtn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        teacherAddBtn.setText("Add");
        teacherAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherAddBtnActionPerformed(evt);
            }
        });

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        tacherEditBtn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        tacherEditBtn.setText("Edit");
        tacherEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tacherEditBtnActionPerformed(evt);
            }
        });

        txtQualification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQualificationActionPerformed(evt);
            }
        });

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmobileActionPerformed(evt);
            }
        });

        staffHeader.setFont(new java.awt.Font("Arial", 3, 26)); // NOI18N
        staffHeader.setText("Staff Details");

        mobile.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        mobile.setText("Mobile");

        staffId.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        staffId.setText("Id");

        qualification.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        qualification.setText("Qualification");

        teacherRemoveBtn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        teacherRemoveBtn.setText("Remove");
        teacherRemoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherRemoveBtnActionPerformed(evt);
            }
        });

        name.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        name.setText("Name");

        teagender.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        teagender.setText("Gender");

        teamale.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        teamale.setText("Male");
        teamale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamaleActionPerformed(evt);
            }
        });

        teafemaile.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        teafemaile.setText("Female");
        teafemaile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teafemaileActionPerformed(evt);
            }
        });

        staffStartingDate.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        staffStartingDate.setText("Post");

        stdClearBtn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        stdClearBtn.setText("Clear");
        stdClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdClearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(qualification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(staffId, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teagender)
                    .addComponent(staffStartingDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(txtDate)
                            .addComponent(txtQualification))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mobile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(teamale)
                        .addGap(83, 83, 83)
                        .addComponent(teafemaile)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(txtmobile)
                    .addComponent(txtName))
                .addGap(91, 91, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tacherEditBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(teacherAddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(teacherRemoveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(stdClearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(177, 177, 177))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(528, 528, 528)
                        .addComponent(staffHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(497, 497, 497)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(staffHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(staffStartingDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(qualification)
                                    .addComponent(txtQualification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(teafemaile)
                                    .addComponent(teamale)
                                    .addComponent(teagender)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stdClearBtn)
                        .addGap(18, 18, 18)
                        .addComponent(teacherRemoveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tacherEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Post", "Mobile", "Qualification", "Gender", "Address"
            }
        ));
        table.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tableAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        showdata.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        showdata.setText("Show Data");
        showdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showdataActionPerformed(evt);
            }
        });

        jMenu1login.setText("Login");
        jMenuBar1.add(jMenu1login);

        jMenu2Student.setText("Student");
        jMenu2Student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2StudentMouseClicked(evt);
            }
        });
        jMenu2Student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2StudentActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2Student);

        jMenu3Teacher.setText("Teacher");
        jMenu3Teacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3TeacherMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3Teacher);

        jMenu4Staff.setText("Staff");
        jMenu4Staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4StaffActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu4Staff);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(575, 575, 575)
                        .addComponent(showdata, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showdata, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void teacherAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherAddBtnActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)table.getModel();
           if (txtName.getText().equals("") ||jTextField9.getText().equals("")||txtDate.getText().equals("")||
                   teaarea.getText().equals("")|| txtQualification.getText().equals("")
                   || txtmobile.getText().equals("")  )
        {JOptionPane.showMessageDialog(this, "Please Enter All Data") ;}
           else
               {String data[] = {jTextField9.getText(),  txtName.getText(), txtDate.getText(),
                            txtmobile.getText(), txtQualification.getText(),gender, teaarea.getText()} ;
               model.addRow (data);}


           //Adding Data into MySql...

        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/studentmanagemament","root","RTnexgen@123");
            PreparedStatement ps=con.prepareStatement("insert into staff  values(?,?,?,?,?,?,?)");

            ps.setString(1,jTextField9.getText());
            ps.setString(2,txtName.getText());
            ps.setString(3,txtDate.getText());
            ps.setString(4,txtmobile.getText());
            ps.setString(5,txtQualification.getText());
            ps.setString(6,gender);
            ps.setString(7,teaarea.getText());
            ps.execute();
            con.close();

            }
        catch (Exception e) {e.printStackTrace();}

    }//GEN-LAST:event_teacherAddBtnActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void tacherEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tacherEditBtnActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)table.getModel();
        //Remove odd data
         int SelectedRowIndex = table.getSelectedRow();
        model.removeRow(SelectedRowIndex);
        //Add new data

           if (txtName.getText().equals("") ||jTextField9.getText().equals("")||txtDate.getText().equals("")||
                   teaarea.getText().equals("")|| txtQualification.getText().equals("")
                   || txtmobile.getText().equals("")  )
        {
            JOptionPane.showMessageDialog(this, "Please Enter All Data") ;

        }
               else
        {
           {String data[] = {jTextField9.getText(),  txtName.getText(), txtDate.getText(),
                            txtmobile.getText(), txtQualification.getText(),gender, teaarea.getText()} ;
               model.addRow (data);}
        }


         //Remove from My Sql

         try{

      // model.removeRow(SelectedRowIndex);

        Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/studentmanagemament","root","RTnexgen@123");
            PreparedStatement pse=con.prepareStatement(" DELETE FROM student WHERE Id=?");
            pse.setString(1,jTextField9.getText());
            pse.execute();
            con.close();
             }catch(Exception ex)
       {
           JOptionPane.showMessageDialog(null, "Exceptiondelete");
       }

         try{
             Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/studentmanagemament","root","RTnexgen@123");
             PreparedStatement ps=con.prepareStatement("insert into student  values(?,?,?,?,?,?,?,?)");
            ps.setString(1,jTextField9.getText());
            ps.setString(2,txtName.getText());
            ps.setString(3,txtDate.getText());
            ps.setString(4,txtmobile.getText());
            ps.setString(5,txtQualification.getText());
            ps.setString(6,gender);
            ps.setString(7,teaarea.getText());
            ps.execute();
            con.close();

           JOptionPane.showMessageDialog(null,"Edited");

       }catch(Exception ex)
       {
           JOptionPane.showMessageDialog(null, "Exception Add");
       }
    }//GEN-LAST:event_tacherEditBtnActionPerformed

    private void txtQualificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQualificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualificationActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobileActionPerformed

    private void teacherRemoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherRemoveBtnActionPerformed
        // TODO add your handling code here:
         try{

        DefaultTableModel model = (DefaultTableModel)table.getModel();
       int SelectedRowIndex = table.getSelectedRow();
       model.removeRow(SelectedRowIndex);
       }catch(Exception ex)
       {
           JOptionPane.showMessageDialog(null, ex);
       }

          try{

      // model.removeRow(SelectedRowIndex);

        Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/studentmanagemament","root","RTnexgen@123");
            PreparedStatement pse=con.prepareStatement(" DELETE FROM student WHERE Id=?");
            pse.setString(1,jTextField9.getText());
            pse.execute();
            con.close();
             }catch(Exception ex)
       {
           JOptionPane.showMessageDialog(null, "Exceptiondelete");
       }
    }//GEN-LAST:event_teacherRemoveBtnActionPerformed

    private void teamaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamaleActionPerformed
        // TODO add your handling code here:.
        gender="Male";
    }//GEN-LAST:event_teamaleActionPerformed

    private void jMenu2StudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2StudentActionPerformed
        // TODO add your handling code here:
        new student().setVisible(true);
    }//GEN-LAST:event_jMenu2StudentActionPerformed

    private void jMenu4StaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4StaffActionPerformed
        // TODO add your handling code here:
        new staff().setVisible(true);
    }//GEN-LAST:event_jMenu4StaffActionPerformed

    private void teafemaileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teafemaileActionPerformed
        // TODO add your handling code here:
        gender="Female";
    }//GEN-LAST:event_teafemaileActionPerformed

    private void stdClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdClearBtnActionPerformed
        // TODO add your handling code here:
        jTextField9.setText("");

        txtName.setText("");
        txtQualification.setText("");
        txtDate.setText("");
        txtmobile.setText("");
        teaarea.setText("");
    }//GEN-LAST:event_stdClearBtnActionPerformed

    private void showdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showdataActionPerformed
        // TODO add your handling code here:

        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/studentmanagemament","root","RTnexgen@123");
            Statement st= con.createStatement();

            String sql ="Select * from staff";
            ResultSet rs= st.executeQuery(sql);

            DefaultTableModel model = (DefaultTableModel)table.getModel();
            while (rs.next()){
                //Add into table

                String data[] = {rs.getString("StaffId"),rs.getString("Name"),rs.getString("StartingDate"),
                    rs.getString("Mobile"),rs.getString("Qualification"),rs.getString("Gender"),
                    rs.getString("Address")};
                model.addRow (data);
            }
            con.close();
        }

        catch (Exception e) {e.printStackTrace();}
    }//GEN-LAST:event_showdataActionPerformed

    private void jMenu2StudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2StudentMouseClicked
        // TODO add your handling code here:
        student st = new student();
    }//GEN-LAST:event_jMenu2StudentMouseClicked

    private void jMenu3TeacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3TeacherMouseClicked
        // TODO add your handling code here:
        teacher te = new teacher();
    }//GEN-LAST:event_jMenu3TeacherMouseClicked

    private void tableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tableAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tableAncestorAdded

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JMenu jMenu1login;
    private javax.swing.JMenu jMenu2Student;
    private javax.swing.JMenu jMenu3Teacher;
    private javax.swing.JMenu jMenu4Staff;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel mobile;
    private javax.swing.JLabel name;
    private javax.swing.JLabel qualification;
    private javax.swing.JButton showdata;
    private javax.swing.JLabel staffHeader;
    private javax.swing.JLabel staffId;
    private javax.swing.JLabel staffStartingDate;
    private javax.swing.JButton stdClearBtn;
    private javax.swing.JTable table;
    private javax.swing.JButton tacherEditBtn;
    private javax.swing.JTextArea teaarea;
    private javax.swing.JButton teacherAddBtn;
    private javax.swing.JButton teacherRemoveBtn;
    private javax.swing.JRadioButton teafemaile;
    private javax.swing.JLabel teagender;
    private javax.swing.JRadioButton teamale;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtQualification;
    private javax.swing.JTextField txtmobile;
    // End of variables declaration//GEN-END:variables
    private String gender;
}