/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.studentmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author RT Nexgen
 */
public class student extends javax.swing.JFrame {

    /**
     * Creates new form student
     */

    private String studentClass,studentSection, gender;


    public student() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gendergroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        studentpanel = new javax.swing.JPanel();
        stdheader = new javax.swing.JLabel();
        mobile = new javax.swing.JLabel();
        stdId = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        stdClass = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        stdtxtId = new javax.swing.JTextField();
        txtCourseid = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtmobile = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        teagender = new javax.swing.JLabel();
        teamale = new javax.swing.JRadioButton();
        teafemale = new javax.swing.JRadioButton();
        stdEditBtn = new javax.swing.JButton();
        stdRemoveBtn = new javax.swing.JButton();
        stdAddBtn = new javax.swing.JButton();
        stdClassCombo = new javax.swing.JComboBox<>();
        stdsection = new javax.swing.JComboBox<>();
        courseId = new javax.swing.JLabel();
        txtSpecialisation1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        stdTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        teaarea = new javax.swing.JTextArea();
        stdClearBtn = new javax.swing.JButton();
        showdata = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuLogin = new javax.swing.JMenu();
        jMenustd = new javax.swing.JMenu();
        jMenuTeacher = new javax.swing.JMenu();
        jMenuStaff = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentpanel.setForeground(new java.awt.Color(153, 255, 255));

        stdheader.setFont(new java.awt.Font("Arial", 3, 26)); // NOI18N
        stdheader.setText("Student's Details");

        mobile.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        mobile.setText("Mobile");

        stdId.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        stdId.setText("Id");

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel13.setText("E-mail");

        name.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        name.setText("Name");

        stdClass.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        stdClass.setText("Standard");

        address.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        address.setText("Address");

        stdtxtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdtxtIdActionPerformed(evt);
            }
        });

        txtCourseid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseidActionPerformed(evt);
            }
        });

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmobileActionPerformed(evt);
            }
        });

        teagender.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        teagender.setText("Gender");

        gendergroup.add(teamale);
        teamale.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        teamale.setText("Male");
        teamale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamaleActionPerformed(evt);
            }
        });

        gendergroup.add(teafemale);
        teafemale.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        teafemale.setText("Female");
        teafemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teafemaleActionPerformed(evt);
            }
        });

        stdEditBtn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        stdEditBtn.setText("Edit");
        stdEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdEditBtnActionPerformed(evt);
            }
        });

        stdRemoveBtn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        stdRemoveBtn.setText("Remove");
        stdRemoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdRemoveBtnActionPerformed(evt);
            }
        });

        stdAddBtn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        stdAddBtn.setText("Add");
        stdAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdAddBtnActionPerformed(evt);
            }
        });

        stdClassCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Class", "XII", "XI", "X", "IX", "VIII", "VII", "VI", "V", "IV", "III", "II", "I" }));
        stdClassCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdClassComboActionPerformed(evt);
            }
        });

        stdsection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Section", "A", "B", "C", "D" }));
        stdsection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdsectionActionPerformed(evt);
            }
        });

        courseId.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        courseId.setText("Course Id ");

        txtSpecialisation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpecialisation1ActionPerformed(evt);
            }
        });

        stdTable.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        stdTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Standard", "E-mail", "Course Id", "Mobile", "Gender", "Address"
            }
        ));
        stdTable.setRowHeight(25);
        stdTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                stdTableAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        stdTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stdTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stdTable);
        if (stdTable.getColumnModel().getColumnCount() > 0) {
            stdTable.getColumnModel().getColumn(0).setResizable(false);
            stdTable.getColumnModel().getColumn(0).setPreferredWidth(15);
            stdTable.getColumnModel().getColumn(6).setResizable(false);
        }

        teaarea.setColumns(20);
        teaarea.setRows(5);
        jScrollPane2.setViewportView(teaarea);

        stdClearBtn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        stdClearBtn.setText("Clear");
        stdClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdClearBtnActionPerformed(evt);
            }
        });

        showdata.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        showdata.setText("Show Data");
        showdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showdataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentpanelLayout = new javax.swing.GroupLayout(studentpanel);
        studentpanel.setLayout(studentpanelLayout);
        studentpanelLayout.setHorizontalGroup(
            studentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentpanelLayout.createSequentialGroup()
                .addGroup(studentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(studentpanelLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(studentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(studentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel13)
                                .addComponent(stdId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(courseId)
                                .addComponent(stdClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(teagender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(studentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(studentpanelLayout.createSequentialGroup()
                                .addComponent(teamale)
                                .addGap(64, 64, 64)
                                .addComponent(teafemale))
                            .addGroup(studentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(studentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(studentpanelLayout.createSequentialGroup()
                                        .addGroup(studentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(stdtxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(studentpanelLayout.createSequentialGroup()
                                                .addComponent(stdClassCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(stdsection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(26, 26, 26))
                                    .addComponent(txtCourseid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtSpecialisation1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(studentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(studentpanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(studentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(studentpanelLayout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)))
                        .addGroup(studentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmobile, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(studentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(studentpanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(studentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(stdAddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addComponent(stdClearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentpanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stdRemoveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(studentpanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showdata, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(316, 316, 316)
                        .addComponent(stdEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stdheader)
                .addGap(379, 379, 379))
            .addGroup(studentpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(studentpanelLayout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        studentpanelLayout.setVerticalGroup(
            studentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentpanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(stdheader, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(studentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentpanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(studentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stdId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stdtxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stdAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(studentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(studentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(stdClass, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(stdClassCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(stdsection, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(stdClearBtn)))
                    .addGroup(studentpanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(studentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(studentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentpanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(studentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(studentpanelLayout.createSequentialGroup()
                                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addGroup(studentpanelLayout.createSequentialGroup()
                                .addGroup(studentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSpecialisation1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(studentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(studentpanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(courseId))
                                    .addGroup(studentpanelLayout.createSequentialGroup()
                                        .addComponent(txtCourseid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 2, Short.MAX_VALUE)))))
                        .addGap(5, 5, 5)
                        .addGroup(studentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teagender)
                            .addComponent(teamale)
                            .addComponent(teafemale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(showdata, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(studentpanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(studentpanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(stdRemoveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(stdEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(studentpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(studentpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jMenuLogin.setText("Login");
        jMenuBar1.add(jMenuLogin);

        jMenustd.setText("Student");
        jMenuBar1.add(jMenustd);

        jMenuTeacher.setText("Teacher");
        jMenuTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTeacherActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuTeacher);

        jMenuStaff.setText("Staff");
        jMenuStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuStaffActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuStaff);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jMenuTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTeacherActionPerformed
                // TODO add your handling code here:
        new teacher().setVisible(true);
    }//GEN-LAST:event_jMenuTeacherActionPerformed

    private void jMenuStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuStaffActionPerformed
        // TODO add your handling code here:
        new staff().setVisible(true);
    }//GEN-LAST:event_jMenuStaffActionPerformed

    private void stdsectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdsectionActionPerformed
        // TODO add your handling code here:

        if (stdsection.getSelectedItem().equals("B"))
        {
            studentSection="B";
        }
        else if (stdsection.getSelectedItem().equals("C"))
        {
            studentSection="C";
        }
        else if (stdsection.getSelectedItem().equals("D"))
        {
            studentSection="D";
        }
        else
        {
            studentSection="A";
        }
    }//GEN-LAST:event_stdsectionActionPerformed

    private void stdClassComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdClassComboActionPerformed
        // TODO add your handling code here:

        if (stdClassCombo.getSelectedItem().equals("I"))
        {
            studentClass="1 ";
        }
        else if(stdClassCombo.getSelectedItem().equals("II"))
        {
            studentClass="2 ";
        }
        else if(stdClassCombo.getSelectedItem().equals("III"))
        {
            studentClass="3 ";
        }
        else if(stdClassCombo.getSelectedItem().equals("IV"))
        {
            studentClass="4 ";
        }
        else if(stdClassCombo.getSelectedItem().equals("V"))
        {
            studentClass="5 ";
        }
        else if(stdClassCombo.getSelectedItem().equals("VI"))
        {
            studentClass="6 ";
        }
        else if(stdClassCombo.getSelectedItem().equals("VII"))
        {
            studentClass="7 ";
        }
        else if(stdClassCombo.getSelectedItem().equals("VIII"))
        {
            studentClass="8 ";
        }

        else if(stdClassCombo.getSelectedItem().equals("IX"))
        {
            studentClass="9 ";
        }
        else if(stdClassCombo.getSelectedItem().equals("XII"))
        {
            studentClass="12 ";
        }
        else if(stdClassCombo.getSelectedItem().equals("X"))
        {
            studentClass="10 ";
        }
        else if(stdClassCombo.getSelectedItem().equals("XI"))
        {
            studentClass="11 ";
        }


    }//GEN-LAST:event_stdClassComboActionPerformed

    private void stdAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdAddBtnActionPerformed
        // TODO add your handling code here:

        //Adding Value into Table...
        DefaultTableModel model = (DefaultTableModel)stdTable.getModel();
        if (stdtxtId.getText().equals("") || teaarea.getText().equals("") || txtName.getText().equals("") || txtCourseid.getText().equals("") ||txtmobile.getText().equals("") )
        {
            JOptionPane.showMessageDialog(this, "Please Enter All Data") ;

        }
        else
        {
            String data[] = {stdtxtId.getText(),  txtName.getText(), (studentClass+studentSection) ,
                                                txtSpecialisation1.getText(), txtCourseid.getText(),txtmobile.getText(),
                                                gender, teaarea.getText()} ;
            model.addRow (data);
        }

        //Adding Data into MySql...

        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/studentmanagemament","root","RTnexgen@123");
            PreparedStatement ps=con.prepareStatement("insert into student  values(?,?,?,?,?,?,?,?)");

            ps.setString(1,stdtxtId.getText());
            ps.setString(2,txtName.getText());
            ps.setString(3,(studentClass+studentSection));
            ps.setString(4,txtSpecialisation1.getText());
            ps.setString(5,txtCourseid.getText());
            ps.setString(6,txtmobile.getText());
            ps.setString(7,gender);
            ps.setString(8,teaarea.getText());
            ps.execute();
            con.close();

            }
        catch (Exception e) {e.printStackTrace();}



    }//GEN-LAST:event_stdAddBtnActionPerformed

    private void stdRemoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdRemoveBtnActionPerformed
        // TODO add your handling code here:
          try{

        DefaultTableModel model = (DefaultTableModel)stdTable.getModel();
       int SelectedRowIndex = stdTable.getSelectedRow();
       model.removeRow(SelectedRowIndex);
        Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/studentmanagemament","root","RTnexgen@123");
            PreparedStatement pse=con.prepareStatement(" DELETE FROM student WHERE Id=?");
            pse.setString(1,stdtxtId.getText());
            pse.execute();
            con.close();

       }catch(Exception ex)
       {
           JOptionPane.showMessageDialog(null, "Exception");
       }

    }//GEN-LAST:event_stdRemoveBtnActionPerformed

    private void stdEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdEditBtnActionPerformed
        // TODO add your handling code here:
        //Remove Value
        DefaultTableModel model = (DefaultTableModel)stdTable.getModel();
       int SelectedRowIndex = stdTable.getSelectedRow();
       model.removeRow(SelectedRowIndex);

        //New Value

        if (stdtxtId.getText().equals("") || teaarea.getText().equals("") || txtName.getText().equals("") || txtCourseid.getText().equals("") ||txtmobile.getText().equals("") )
        {
            JOptionPane.showMessageDialog(this, "Please Enter All Data") ;

        }
        else
        {
            String data[] = {stdtxtId.getText(),  txtName.getText(), (studentClass+studentSection) ,
                                                txtSpecialisation1.getText(), txtCourseid.getText(),txtmobile.getText(),
                                                gender, teaarea.getText()} ;
            model.addRow (data);
        }

       //Remove from My Sql

         try{

      // model.removeRow(SelectedRowIndex);

        Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/studentmanagemament","root","RTnexgen@123");
            PreparedStatement pse=con.prepareStatement(" DELETE FROM student WHERE Id=?");
            pse.setString(1,stdtxtId.getText());
            pse.execute();
            con.close();
             }catch(Exception ex)
       {
           JOptionPane.showMessageDialog(null, "Exceptiondelete");
       }

         try{
             Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/studentmanagemament","root","RTnexgen@123");
             PreparedStatement ps=con.prepareStatement("insert into student  values(?,?,?,?,?,?,?,?)");
            ps.setString(1,stdtxtId.getText());
            ps.setString(2,txtName.getText());
            ps.setString(3,(studentClass+studentSection));
            ps.setString(4,txtSpecialisation1.getText());
            ps.setString(5,txtCourseid.getText());
            ps.setString(6,txtmobile.getText());
            ps.setString(7,gender);
            ps.setString(8,teaarea.getText());
            ps.execute();
           JOptionPane.showMessageDialog(null,"Edited");
            con.close();

       }catch(Exception ex)
       {
           JOptionPane.showMessageDialog(null, "Exception Add");
       }
    }//GEN-LAST:event_stdEditBtnActionPerformed

    private void teamaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamaleActionPerformed
        // TODO add your handling code here:

        gender = "Male";
    }//GEN-LAST:event_teamaleActionPerformed

    private void txtmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobileActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtCourseidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseidActionPerformed

    private void stdtxtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdtxtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdtxtIdActionPerformed

    private void txtSpecialisation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpecialisation1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpecialisation1ActionPerformed

    private void teafemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teafemaleActionPerformed
        // TODO add your handling code here:
        gender = "Female";
    }//GEN-LAST:event_teafemaleActionPerformed

    private void stdTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stdTableMouseClicked
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel)stdTable.getModel();

        var tblId = model.getValueAt(stdTable.getSelectedRow(), 0);
        stdtxtId.setText(tblId.toString());

        var tblName = model.getValueAt(stdTable.getSelectedRow(), 1);
        txtName.setText(tblName.toString());



        var tblEmail = model.getValueAt(stdTable.getSelectedRow(), 3);
        txtSpecialisation1.setText(tblEmail.toString());

        var tblCourseId = model.getValueAt(stdTable.getSelectedRow(), 4);
        txtCourseid.setText(tblCourseId.toString());

        var tblMobile = model.getValueAt(stdTable.getSelectedRow(), 5);
        txtmobile.setText(tblMobile.toString());


        var tblAddress = model.getValueAt(stdTable.getSelectedRow(), 7);
        teaarea.setText(tblAddress.toString());


    }//GEN-LAST:event_stdTableMouseClicked

    private void stdClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdClearBtnActionPerformed
        // TODO add your handling code here:
        stdtxtId.setText("");

        txtName.setText("");
        txtCourseid.setText("");
        txtSpecialisation1.setText("");
        txtmobile.setText("");
        teaarea.setText("");



    }//GEN-LAST:event_stdClearBtnActionPerformed

    private void stdTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_stdTableAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_stdTableAncestorAdded

    private void showdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showdataActionPerformed
        // TODO add your handling code here:
                try{
         Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/studentmanagemament","root","RTnexgen@123");
        Statement st= con.createStatement();
            String sql ="Select * from student";
            ResultSet rs= st.executeQuery(sql);
            DefaultTableModel model = (DefaultTableModel)stdTable.getModel();
            while (rs.next()){
               //Add into table
                String data[] = {rs.getString("Id"),rs.getString("Name"),rs.getString("standard"),
                    rs.getString("Email"),rs.getString("Course_Id"),rs.getString("Mobile"),
                    rs.getString("Gender"),rs.getString("Address")};
                            model.addRow (data);
            }
            con.close();
                }
            catch (Exception e) {e.printStackTrace();}
    }//GEN-LAST:event_showdataActionPerformed




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel courseId;
    private javax.swing.ButtonGroup gendergroup;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuLogin;
    private javax.swing.JMenu jMenuStaff;
    private javax.swing.JMenu jMenuTeacher;
    private javax.swing.JMenu jMenustd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mobile;
    private javax.swing.JLabel name;
    private javax.swing.JButton showdata;
    private javax.swing.JButton stdAddBtn;
    private javax.swing.JLabel stdClass;
    private javax.swing.JComboBox<String> stdClassCombo;
    private javax.swing.JButton stdClearBtn;
    private javax.swing.JButton stdEditBtn;
    private javax.swing.JLabel stdId;
    private javax.swing.JButton stdRemoveBtn;
    private javax.swing.JTable stdTable;
    private javax.swing.JLabel stdheader;
    private javax.swing.JComboBox<String> stdsection;
    private javax.swing.JTextField stdtxtId;
    private javax.swing.JPanel studentpanel;
    private javax.swing.JTextArea teaarea;
    private javax.swing.JRadioButton teafemale;
    private javax.swing.JLabel teagender;
    private javax.swing.JRadioButton teamale;
    private javax.swing.JTextField txtCourseid;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSpecialisation1;
    private javax.swing.JTextField txtmobile;
    // End of variables declaration//GEN-END:variables
}
