/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.studentmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RT Nexgen
 */
public class teacher extends javax.swing.JFrame {

    /**
     * Creates new form teacher
     */
    public teacher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        address = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        teaarea = new javax.swing.JTextArea();
        teacherAddBtn = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        tacherEditBtn = new javax.swing.JButton();
        txtSpecialisation = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtName = new javax.swing.JTextField();
        txtmobile = new javax.swing.JTextField();
        theader = new javax.swing.JLabel();
        mobile = new javax.swing.JLabel();
        tea_id = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        teacherRemoveBtn = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        teagender = new javax.swing.JLabel();
        teamale = new javax.swing.JRadioButton();
        teafemaile = new javax.swing.JRadioButton();
        lclass = new javax.swing.JLabel();
        qualification = new javax.swing.JLabel();
        txtqualification = new javax.swing.JTextField();
        stdClearBtn = new javax.swing.JButton();
        stdClassCombo = new javax.swing.JComboBox<>();
        stdsection = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        teacherTable = new javax.swing.JTable();
        showdata = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1login = new javax.swing.JMenu();
        jMenu2Student = new javax.swing.JMenu();
        jMenu3Teacher = new javax.swing.JMenu();
        jMenu4Staff = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        address.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        address.setText("Address");

        teaarea.setColumns(20);
        teaarea.setRows(5);
        jScrollPane3.setViewportView(teaarea);

        teacherAddBtn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        teacherAddBtn.setText("Add");
        teacherAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherAddBtnActionPerformed(evt);
            }
        });

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        tacherEditBtn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        tacherEditBtn.setText("Edit");
        tacherEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tacherEditBtnActionPerformed(evt);
            }
        });

        txtSpecialisation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpecialisationActionPerformed(evt);
            }
        });

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmobileActionPerformed(evt);
            }
        });

        theader.setFont(new java.awt.Font("Arial", 3, 26)); // NOI18N
        theader.setText("Teacher's Details");

        mobile.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        mobile.setText("Mobile");

        tea_id.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        tea_id.setText("Id");

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel13.setText("Specialisation");

        teacherRemoveBtn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        teacherRemoveBtn.setText("Remove");
        teacherRemoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherRemoveBtnActionPerformed(evt);
            }
        });

        name.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        name.setText("Name");

        teagender.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        teagender.setText("Gender");

        buttonGroup1.add(teamale);
        teamale.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        teamale.setText("Male");
        teamale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(teafemaile);
        teafemaile.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        teafemaile.setText("Female");
        teafemaile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teafemaileActionPerformed(evt);
            }
        });

        lclass.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lclass.setText("Class");

        qualification.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        qualification.setText("Qualification");

        txtqualification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqualificationActionPerformed(evt);
            }
        });

        stdClearBtn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        stdClearBtn.setText("Clear");
        stdClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdClearBtnActionPerformed(evt);
            }
        });

        stdClassCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Class", "XII", "XI", "X", "IX", "VIII", "VII", "VI", "V", "IV", "III", "II", "I" }));
        stdClassCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdClassComboActionPerformed(evt);
            }
        });

        stdsection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Section", "A", "B", "C", "D" }));
        stdsection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdsectionActionPerformed(evt);
            }
        });

        teacherTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Class", "Mobile", "Qualification", "Specialisation", "Gender", "Address"
            }
        ));
        teacherTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(teacherTable);

        showdata.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        showdata.setText("Show Data");
        showdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showdataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lclass, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tea_id, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(teagender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(qualification, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(teamale)
                        .addGap(54, 54, 54)
                        .addComponent(teafemaile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showdata, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtqualification, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSpecialisation, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(stdClassCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(stdsection, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mobile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(txtmobile)
                    .addComponent(txtName))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tacherEditBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(teacherAddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(teacherRemoveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(stdClearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(177, 177, 177))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(427, 427, 427)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(457, 457, 457)
                        .addComponent(theader, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1063, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(theader, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tea_id, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(teacherRemoveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(tacherEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stdClearBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtmobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lclass, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stdClassCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stdsection, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(qualification, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtqualification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(showdata, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(txtSpecialisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(teagender)
                                        .addComponent(teamale)
                                        .addComponent(teafemaile))
                                    .addGap(15, 15, 15))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        jMenu1login.setText("Login");
        jMenuBar1.add(jMenu1login);

        jMenu2Student.setText("Student");
        jMenu2Student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2StudentActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2Student);

        jMenu3Teacher.setText("Teacher");
        jMenuBar1.add(jMenu3Teacher);

        jMenu4Staff.setText("Staff");
        jMenu4Staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4StaffActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu4Staff);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teacherAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherAddBtnActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)teacherTable.getModel();
           if (txtName.getText().equals("") ||txtId.getText().equals("")|| teacherClass.equals("")|| teacherSection.equals("")||
                   teaarea.getText().equals("")|| txtSpecialisation.getText().equals("")
                   || txtmobile.getText().equals("") || gender.equals("")||
                   txtqualification.getText().equals("") )
        {
            JOptionPane.showMessageDialog(this, "Please Enter All Data") ;
            
        }        
        else
        {
            String data[] = {txtId.getText(),  txtName.getText(), (teacherClass+teacherSection),
                            txtmobile.getText(), txtqualification.getText(),txtSpecialisation.getText(),
                                                gender, teaarea.getText()} ;
            model.addRow (data);
        }
           
        
           //Adding Data into MySql...
        
        try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
                    "jdbc:mysql://localhost:3306/studentmanagemament","root","RTnexgen@123");
            PreparedStatement ps=con.prepareStatement("insert into teacher  values(?,?,?,?,?,?,?,?)");  
            
            ps.setString(1,txtId.getText());  
            ps.setString(2,txtName.getText());
            ps.setString(3,(teacherClass+teacherSection));  
            ps.setString(4,txtmobile.getText());  
            ps.setString(5,txtqualification.getText());  
            ps.setString(6,txtSpecialisation.getText());
            ps.setString(7,gender);
            ps.setString(8,teaarea.getText());  
            ps.execute();
            con.close();

            }
        catch (Exception e) {e.printStackTrace();}  


    }//GEN-LAST:event_teacherAddBtnActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void tacherEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tacherEditBtnActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)teacherTable.getModel();
        //Remove odd data
         int SelectedRowIndex = teacherTable.getSelectedRow();
        model.removeRow(SelectedRowIndex);
        //Add new data
       
           if (txtName.getText().equals("") ||txtId.getText().equals("")||
                   teaarea.getText().equals("")|| txtSpecialisation.getText().equals("")
                   || txtmobile.getText().equals("") ||
                   txtqualification.getText().equals("") )
        {
            JOptionPane.showMessageDialog(this, "Please Enter All Data") ;
            
        }        
               else
        {
            String data[] = {txtId.getText(),  txtName.getText(), (teacherClass+teacherSection),
                            txtmobile.getText(), txtqualification.getText(),txtSpecialisation.getText(),
                                                gender, teaarea.getText()} ;
            model.addRow (data);
        }
           
           
         //Remove from My Sql
        
         try{             
        
      // model.removeRow(SelectedRowIndex);
      
        Class.forName("com.mysql.cj.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
                    "jdbc:mysql://localhost:3306/studentmanagemament","root","RTnexgen@123");
            PreparedStatement pse=con.prepareStatement(" DELETE FROM student WHERE Id=?");
            pse.setString(1,txtId.getText());
            pse.execute();
            con.close();
             }catch(Exception ex)
       {
           JOptionPane.showMessageDialog(null, "Exceptiondelete");
       }
              
         try{ 
             Class.forName("com.mysql.cj.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
                    "jdbc:mysql://localhost:3306/studentmanagemament","root","RTnexgen@123");
             PreparedStatement ps=con.prepareStatement("insert into student  values(?,?,?,?,?,?,?,?)");
            ps.setString(1,txtId.getText());  
            ps.setString(2,txtName.getText());
            ps.setString(3,(teacherClass+teacherSection));  
            ps.setString(4,txtmobile.getText());  
            ps.setString(5,txtqualification.getText());  
            ps.setString(6,txtSpecialisation.getText());
            ps.setString(7,gender);
            ps.setString(8,teaarea.getText());  
            ps.execute();
            con.close();

           JOptionPane.showMessageDialog(null,"Edited"); 
       
       }catch(Exception ex)
       {
           JOptionPane.showMessageDialog(null, "Exception Add");
       }

    }//GEN-LAST:event_tacherEditBtnActionPerformed

    private void txtSpecialisationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpecialisationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpecialisationActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmobileActionPerformed
        // TODO add your handling code 
    }//GEN-LAST:event_txtmobileActionPerformed

    private void teacherRemoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherRemoveBtnActionPerformed
        // TODO add your handling code here:
         try{
              
        DefaultTableModel model = (DefaultTableModel)teacherTable.getModel();
       int SelectedRowIndex = teacherTable.getSelectedRow();
       model.removeRow(SelectedRowIndex);
        Class.forName("com.mysql.cj.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
                    "jdbc:mysql://localhost:3306/studentmanagemament","root","RTnexgen@123");
            PreparedStatement pse=con.prepareStatement(" DELETE FROM student WHERE Id=?");
            pse.setString(1,txtId.getText());
            pse.execute();
            con.close();
       
       }catch(Exception ex)
       {
           JOptionPane.showMessageDialog(null, "Exception");
       }
    }//GEN-LAST:event_teacherRemoveBtnActionPerformed

    private void teamaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamaleActionPerformed
        // TODO add your handling code here:
        gender="Male";
    }//GEN-LAST:event_teamaleActionPerformed

    private void jMenu2StudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2StudentActionPerformed
        // TODO add your handling code here:
        new student().setVisible(true);
    }//GEN-LAST:event_jMenu2StudentActionPerformed

    private void jMenu4StaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4StaffActionPerformed
        // TODO add your handling code here:
        new staff().setVisible(true);
    }//GEN-LAST:event_jMenu4StaffActionPerformed

    private void txtqualificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqualificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqualificationActionPerformed

    private void stdClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdClearBtnActionPerformed
        // TODO add your handling code here:
        txtId.setText("");

        txtName.setText("");
        txtqualification.setText("");
        txtSpecialisation.setText("");
        txtmobile.setText("");
        teaarea.setText("");

    }//GEN-LAST:event_stdClearBtnActionPerformed

    private void stdClassComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdClassComboActionPerformed
        // TODO add your handling code here:

        if (stdClassCombo.getSelectedItem().equals("I"))
        {
            teacherClass="1 ";
        }
        else if(stdClassCombo.getSelectedItem().equals("II"))
        {
            teacherClass="2 ";
        }
        else if(stdClassCombo.getSelectedItem().equals("III"))
        {
            teacherClass="3 ";
        }
        else if(stdClassCombo.getSelectedItem().equals("IV"))
        {
            teacherClass="4 ";
        }
        else if(stdClassCombo.getSelectedItem().equals("V"))
        {
            teacherClass="5 ";
        }
        else if(stdClassCombo.getSelectedItem().equals("VI"))
        {
            teacherClass="6 ";
        }
        else if(stdClassCombo.getSelectedItem().equals("VII"))
        {
            teacherClass="7 ";
        }
        else if(stdClassCombo.getSelectedItem().equals("VIII"))
        {
            teacherClass="8 ";
        }

        else if(stdClassCombo.getSelectedItem().equals("IX"))
        {
            teacherClass="9 ";
        }
        else if(stdClassCombo.getSelectedItem().equals("XII"))
        {
            teacherClass="12 ";
        }
        else if(stdClassCombo.getSelectedItem().equals("X"))
        {
            teacherClass="10 ";
        }
        else if(stdClassCombo.getSelectedItem().equals("XI"))
        {
            teacherClass="11 ";
        }

    }//GEN-LAST:event_stdClassComboActionPerformed

    private void stdsectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdsectionActionPerformed
        // TODO add your handling code here:

        if (stdsection.getSelectedItem().equals("B"))
        {
            teacherSection="B";
        }
        else if (stdsection.getSelectedItem().equals("C"))
        {
            teacherSection="C";
        }
        else if (stdsection.getSelectedItem().equals("D"))
        {
            teacherSection="D";
        }
        else
        {
            teacherSection="A";
        }
    }//GEN-LAST:event_stdsectionActionPerformed

    private void teafemaileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teafemaileActionPerformed
        // TODO add your handling code here:
        gender="Female";
    }//GEN-LAST:event_teafemaileActionPerformed

    private void teacherTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherTableMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)teacherTable.getModel();
       
        var tblId = model.getValueAt(teacherTable.getSelectedRow(), 0);
        txtId.setText(tblId.toString());
        
        var tblName = model.getValueAt(teacherTable.getSelectedRow(), 1);
        txtName.setText(tblName.toString());        
            
        var tblmobile = model.getValueAt(teacherTable.getSelectedRow(), 7);
        txtmobile.setText(tblmobile.toString()); 
        
        var tblCourseId = model.getValueAt(teacherTable.getSelectedRow(), 4);
        txtqualification.setText(tblCourseId.toString());    
        
        var tblSpecialisation = model.getValueAt(teacherTable.getSelectedRow(), 4);
        txtSpecialisation.setText(tblSpecialisation.toString());    
       
                
        var tblAddress = model.getValueAt(teacherTable.getSelectedRow(), 7);
        teaarea.setText(tblAddress.toString());        
    }//GEN-LAST:event_teacherTableMouseClicked

    private void showdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showdataActionPerformed
        // TODO add your handling code here:

        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/studentmanagemament","root","RTnexgen@123");
            Statement st= con.createStatement();

            String sql ="Select * from teacher";
            ResultSet rs= st.executeQuery(sql);

            DefaultTableModel model = (DefaultTableModel)teacherTable.getModel();
            while (rs.next()){
                //Add into table

                String data[] = {rs.getString("TeacherId"),rs.getString("Name"),rs.getString("Class"),
                    rs.getString("Mobile"),rs.getString("Qualification"),rs.getString("Specialisation"),
                    rs.getString("Gender"),rs.getString("Address")};
                model.addRow (data);
            }
            con.close();
        }

        catch (Exception e) {e.printStackTrace();}
    }//GEN-LAST:event_showdataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JMenu jMenu1login;
    private javax.swing.JMenu jMenu2Student;
    private javax.swing.JMenu jMenu3Teacher;
    private javax.swing.JMenu jMenu4Staff;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lclass;
    private javax.swing.JLabel mobile;
    private javax.swing.JLabel name;
    private javax.swing.JLabel qualification;
    private javax.swing.JButton showdata;
    private javax.swing.JComboBox<String> stdClassCombo;
    private javax.swing.JButton stdClearBtn;
    private javax.swing.JComboBox<String> stdsection;
    private javax.swing.JButton tacherEditBtn;
    private javax.swing.JLabel tea_id;
    private javax.swing.JTextArea teaarea;
    private javax.swing.JButton teacherAddBtn;
    private javax.swing.JButton teacherRemoveBtn;
    private javax.swing.JTable teacherTable;
    private javax.swing.JRadioButton teafemaile;
    private javax.swing.JLabel teagender;
    private javax.swing.JRadioButton teamale;
    private javax.swing.JLabel theader;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSpecialisation;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtqualification;
    // End of variables declaration//GEN-END:variables
    private String teacherClass="";
    private String teacherSection="";
    private String gender="";
}
